// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtn9cBUp2uv-x7PFngFelAbGMLBe9ef3Q',
    appId: '1:824210106596:web:8027e446cbe1b4b50464f1',
    messagingSenderId: '824210106596',
    projectId: 'tyamo-00',
    authDomain: 'tyamo-00.firebaseapp.com',
    storageBucket: 'tyamo-00.appspot.com',
    measurementId: 'G-B844JRY357',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzODxt23L26H1LAbASfMqNS3xdqcAACU8',
    appId: '1:824210106596:ios:2b184e4df2c753d30464f1',
    messagingSenderId: '824210106596',
    projectId: 'tyamo-00',
    storageBucket: 'tyamo-00.appspot.com',
    iosBundleId: 'com.example.tyamo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzODxt23L26H1LAbASfMqNS3xdqcAACU8',
    appId: '1:824210106596:ios:2b184e4df2c753d30464f1',
    messagingSenderId: '824210106596',
    projectId: 'tyamo-00',
    storageBucket: 'tyamo-00.appspot.com',
    iosBundleId: 'com.example.tyamo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtn9cBUp2uv-x7PFngFelAbGMLBe9ef3Q',
    appId: '1:824210106596:web:e988b9d225ec3f480464f1',
    messagingSenderId: '824210106596',
    projectId: 'tyamo-00',
    authDomain: 'tyamo-00.firebaseapp.com',
    storageBucket: 'tyamo-00.appspot.com',
    measurementId: 'G-JCRGZBN1H4',
  );
}
